server:
  port: 8080
  error:
    include_message: always
spring:
  application:
    name: booking_system
  datasource:
    url: "jdbc:postgresql://localhost:5432/bookingdb"
    username: david
    password: password
#    Postgres driver-class-name: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
#    flyway schemas: bookingDB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true



